### PR TITLE
Add quick access to cmds [maybe not quick access]

### PR DESCRIPTION
**Pull request by HaveFUNRICH**

### CODE REVIEW

**Comment by HaveFUNRICH** [comment]
Don't ask why it call diagnostic because I don't know what name it

**Comment by HaveFUNRICH** [comment]
Very good I type 
Diagnostic
to
diagnotic

**Comment by HaveFUNRICH** [comment]
**_generating excuse_**
I have to go I have homework

**Review by Tpelaaja — APPROVED** [review]

**Review by Vukkyy — COMMENTED** [review]
what's the point of this
i really don't see the point

**Comment by HaveFUNRICH** [comment]
> what's the point of this
> i really don't see the point

hehehhehhehehehehehehehehehehehehehehehe

**Comment by HaveFUNRICH** [comment]
walkx what the fuck is auto-merge

**Comment by WalkxCode** [comment]
Not needed.

**Pull request closed without merging**
