### PR TITLE
Wallet checking

### PR DESCRIPTION
**Pull request by HaveFUNRICH**
# SaladCLI v8.1 (or whatever)

check wallet if the wallet are correct
it will automatically tell you that 
wallet unknown, run anyway?
1. Yes
2. No

### CODE REVIEW

**Comment by HaveFUNRICH** [comment]
Disclaimer: This pull does not come with bug fix region

**Comment by HaveFUNRICH** [comment]
(disclaimer: no salad cli+ support it for mining only becase yersterday it was 11 am i just close this shit for now)

**Comment by HaveFUNRICH** [comment]
close due to: I will port this shit to #20 Pull request and Salad cli+ auth versoin.............

**Comment by HaveFUNRICH** [comment]
my keyboardx has a stroke

**Comment by WalkxCode** [comment]
Make it actually work and than I'll look at it.

**Pull request closed without merging**
