### PR TITLE
remove all py command calls

### PR DESCRIPTION
**Pull request by meow6969**
more info in [this](https://github.com/WalkxCode/SaladCLI_Plus/issues/8) issue

### CODE REVIEW

**Comment by ytJulikus** [comment]
> more info in [this](https://github.com/WalkxCode/SaladCLI_Plus/issues/8) issue

what?

**Comment by WalkxCode** [comment]
You forgot to replace alot of them. I will replace all of them later today and make a new release.

**Comment by meow6969** [comment]
ah yes, i forgot the code is duplicated 3 times, i will fix the other 3 versions and will update my fork

**Comment by WalkxCode** [comment]
Yes, also that. But alot of them are still not replaced

**Comment by meow6969** [comment]
okay, i have replaced the rest of them it is ready to be merged
image

**Comment by TomerGamerTV** [comment]
i can how download the new version?

**Pull request merged**
